apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbp-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbp-auth
  template:
    metadata:
      labels:
        app: tbp-auth
    spec:
      containers:
        - name: auth
          image: ghcr.io/lobothedark/tbp-auth:latest
          ports:
            - containerPort: 80
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: DB_HOST
            value: "10.43.139.26"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "tbp_user"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "i*DV5-E.UM6YB_~}-TcP39TRbseZ3R~R"
---
apiVersion: v1
kind: Service
metadata:
  name: tbp-auth
spec:
  selector:
    app: tbp-auth
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31002
  type: LoadBalancer
