apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbp-backend
  labels:
    app: tbp-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: tbp-backend
  template:
    metadata:
      labels:
        app: tbp-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 8080