apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbp-frontend
  labels:
    app: tbp-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: tbp-frontend
  template:
    metadata:
      labels:
        app: tbp-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80