apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.loki.ingress.hostname | quote }}
      http:
        paths:
          - path: /loki(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: tbp-stack-loki
                port:
                  number: 3100
