apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tempo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.tempo.ingress.hostname | quote }}
      http:
        paths:
          - path: /tempo(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: tbp-stack-tempo
                port:
                  number: 3200
