# Chart.yaml
apiVersion: v2
name: tbp-cluster-stack
description: "Umbrella Chart: TBP apps + Monitoring (Prometheus, Grafana, Loki, Tempo) + Ingress"
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: "70.9.0"      # Latest available version in prometheus-community repo
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: loki-stack
    version: "2.10.2"      # Matches version in grafana helm-charts
    repository: "https://grafana.github.io/helm-charts"
  - name: tempo
    version: "1.21.0"      # Matches version in grafana helm-charts
    repository: "https://grafana.github.io/helm-charts"
  - name: ingress-nginx
    version: 4.10.1
    repository: https://kubernetes.github.io/ingress-nginx