apiVersion: v1
kind: Service
metadata:
  name: tbp-backend
spec:
  type: LoadBalancer
  selector:
    app: tbp-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31001